x-common-variables: &common-variables
  PING_IDENTITY_ACCEPT_EULA: "YES"
  PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
  PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
  PING_IDENTITY_PASSWORD: "2FederateM0re"

services:
  pingfederate-1:
    image: pingidentity/pingfederate:12.2.0-latest
    environment:
      <<: *common-variables
      PF_ADMIN_USER_PASSWORD: "2FederateM0re"
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingfederate/instance/:/tmp/server-profile/server-profiles/pingfederate/
      - ./certificates:/opt/in/certificates
      - pingfederate-out-1:/opt/out
    networks:
      - dive25-net
    ports:
      - "9999:9999"
      - "9031:9031"
    tmpfs:
      - /tmp:exec,mode=1777

  pingfederate-2:
    image: pingidentity/pingfederate:12.2.0-latest
    environment:
      <<: *common-variables
      PF_ADMIN_USER_PASSWORD: "2FederateM0re"
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingfederate/instance/:/tmp/server-profile/server-profiles/pingfederate/
      - ./certificates:/opt/in/certificates
      - pingfederate-out-2:/opt/out
    networks:
      - dive25-net
    ports:
      - "9998:9999"
      - "9032:9031"
    tmpfs:
      - /tmp:exec,mode=1777

  pingaccess-1:
    image: pingidentity/pingaccess:8.2.0-latest
    environment:
      <<: *common-variables
      PA_ADMIN_PASSWORD_INITIAL: "2FederateM0re"
      PA_ADMIN_USER_PASSWORD: "2FederateM0re"
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingaccess/instance/:/tmp/server-profile/server-profiles/pingaccess/
      - ./certificates:/opt/in/certificates
      - pingaccess-out-1:/opt/out
    networks:
      - dive25-net
    ports:
      - "9000:9000"
      - "5001:5000"
    tmpfs:
      - /tmp:exec,mode=1777

  pingaccess-2:
    image: pingidentity/pingaccess:8.2.0-latest
    environment:
      <<: *common-variables
      PA_ADMIN_PASSWORD_INITIAL: "2FederateM0re"
      PA_ADMIN_USER_PASSWORD: "2FederateM0re"
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingaccess/instance/:/tmp/server-profile/server-profiles/pingaccess/
      - ./certificates:/opt/in/certificates
      - pingaccess-out-2:/opt/out
    networks:
      - dive25-net
    ports:
      - "9001:9000"
      - "5002:5000"
    tmpfs:
      - /tmp:exec,mode=1777

  pingdirectory-1:
    image: pingidentity/pingdirectory:10.2.0.0-latest
    environment:
      <<: *common-variables
      PD_ADMIN_USER_PASSWORD: "2FederateM0re"
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingdirectory/instance/:/tmp/server-profile/server-profiles/pingdirectory/
      - ./certificates:/opt/in/certificates
      - pingdirectory-out-1:/opt/out
    networks:
      - dive25-net
    ports:
      - "1389:389"
      - "1636:636"
    tmpfs:
      - /tmp:exec,mode=1777

  pingdirectory-2:
    image: pingidentity/pingdirectory:10.2.0.0-latest
    environment:
      <<: *common-variables
      PD_ADMIN_USER_PASSWORD: "2FederateM0re"
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingdirectory/instance/:/tmp/server-profile/server-profiles/pingdirectory/
      - ./certificates:/opt/in/certificates
      - pingdirectory-out-2:/opt/out
    networks:
      - dive25-net
    ports:
      - "1390:389"
      - "1637:636"
    tmpfs:
      - /tmp:exec,mode=1777

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3050:4000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

networks:
  dive25-net:
    driver: bridge

volumes:
  pingfederate-out-1:
  pingfederate-out-2:
  pingaccess-out-1:
  pingaccess-out-2:
  pingdirectory-out-1:
  pingdirectory-out-2: