services:
  fix-cert-permissions:
    image: busybox
    command: ["sh", "-c", "chmod -R 755 /certificates/prod"]
    volumes:
      - ./certificates/prod:/certificates/prod
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "test -d /certificates/prod"]
      interval: 5s
      timeout: 3s
      retries: 3

  pingfederate:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    environment:
      - PF_LOG_LEVEL=INFO
    ports:
      - "9031:9031"     # Runtime port (SSL)
      - "9999:9999"    # Admin console (internal only)
    volumes:
      - ./certificates/prod:/opt/certificates/prod
      - ./layered_profiles:/opt/serverprofiles
      - ./scripts:/scripts
    depends_on:
      fix-cert-permissions:
        condition: service_completed_successfully
      pingdirectory:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    entrypoint: ["/scripts/wait-for-it.sh", "pingdirectory:1389", "-t", "60", "--", "/opt/entrypoint.sh"]

  pingaccess:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    env_file:
      - .env
    environment:
      - PA_LOG_LEVEL=INFO
      - PING_IDENTITY_PASSWORD=${PING_IDENTITY_PASSWORD}
    ports:
      - "3000:3000"    # Runtime port
      - "9000:9000"    # Admin console (internal only)
    networks:
      - dive25-net
    volumes:
      - ./layered_profiles:/opt/serverprofiles
      - ./scripts:/scripts
    command: ["/run.sh"]
    depends_on:
      pingfederate:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    entrypoint: ["/scripts/wait-for-it.sh", "pingfederate:9031", "-t", "60", "--", "/opt/entrypoint.sh"]

  pingdirectory:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    environment:
      - PD_LOG_LEVEL=INFO
    ports:
      - "1636:636"      # LDAPS
      - "1389:389"      # LDAP
    volumes:
      - ./layered_profiles:/opt/serverprofiles
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - dive25-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    ports:
      - "3050:4000"
    networks:
      - dive25-net
    command: ["/run.sh"]
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build: ./src/backend
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      pingfederate:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  dive25-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16