version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    environment:
      - VITE_API_URL=https://api.dive25.com
      - VITE_KEYCLOAK_URL=https://auth.dive25.com
      - VITE_KEYCLOAK_REALM=dive25
      - VITE_KEYCLOAK_CLIENT_ID=dive25-frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://dive25:${DB_PASSWORD}@db:5432/dive25
      - KEYCLOAK_URL=https://auth.dive25.com
      - KEYCLOAK_REALM=dive25
      - KEYCLOAK_CLIENT_ID=dive25-api
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dive25
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=dive25

  kong:
    image: kong:3.4
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml

volumes:
  postgres_data: