version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:6969
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=dive25
      - VITE_KEYCLOAK_CLIENT_ID=dive25-frontend-dev

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "6969:6969"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dive25:dive25@db:5432/dive25_dev
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=dive25
      - KEYCLOAK_CLIENT_ID=dive25-api-dev
      - KEYCLOAK_CLIENT_SECRET=development_secret

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dive25
      - POSTGRES_PASSWORD=dive25
      - POSTGRES_DB=dive25_dev

volumes:
  postgres_dev_data: