services:
  pingfederate:
    container_name: pingfederate
    ports:
      - "9999:9999"  # Admin console
      - "9031:9031"  # Runtime port
    environment:
      - PF_LOG_LEVEL=DEBUG
      - SERVER_PROFILE_PATH=server-profiles/pingfederate
      - SERVER_PROFILE_BRANCH=develop

  pingaccess:
    container_name: pingaccess
    ports:
      - "9000:9000"  # Admin console
      - "3000:3000"  # Runtime port
    environment:
      - PA_LOG_LEVEL=DEBUG
      - SERVER_PROFILE_PATH=server-profiles/pingaccess
      - SERVER_PROFILE_BRANCH=develop

  pingdirectory:
    container_name: pingdirectory
    ports:
      - "1636:636"   # LDAPS
      - "1389:389"   # LDAP
    environment:
      - SERVER_PROFILE_PATH=server-profiles/pingdirectory
      - SERVER_PROFILE_BRANCH=develop