services:
  pingfederate:
    container_name: pingfederate
    ports:
      - "9999:9999"  # Admin console
      - "9031:9031"  # Runtime port
    environment:
      - PF_LOG_LEVEL=DEBUG
      - SERVER_PROFILE_PATH=server-profiles/pingfederate
      - SERVER_PROFILE_BRANCH=develop
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      pingdirectory:
        condition: service_healthy
    entrypoint: ["/scripts/wait-for-it.sh", "pingdirectory:1389", "-t", "60", "--", "/opt/entrypoint.sh"]

  pingaccess:
    container_name: pingaccess
    ports:
      - "9000:9000"  # Admin console
      - "3000:3000"  # Runtime port
    environment:
      - PA_LOG_LEVEL=DEBUG
      - SERVER_PROFILE_PATH=server-profiles/pingaccess
      - SERVER_PROFILE_BRANCH=develop
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      pingfederate:
        condition: service_healthy
    entrypoint: ["/scripts/wait-for-it.sh", "pingfederate:9031", "-t", "60", "--", "/opt/entrypoint.sh"]

  pingdirectory:
    container_name: pingdirectory
    ports:
      - "1636:636"   # LDAPS
      - "1389:389"   # LDAP
    environment:
      - SERVER_PROFILE_PATH=server-profiles/pingdirectory
      - SERVER_PROFILE_BRANCH=develop
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  dive25-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16