# helm/values-prod.yaml
global:
  environment: production
  domain: dive25.com

pingfederate:
  replicas: 2
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"

pingaccess:
  replicas: 2
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

api:
  replicas: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

monitoring:
  enabled: true
  grafana:
    adminPassword: ${GRAFANA_ADMIN_PASSWORD}
  alertmanager:
    receivers:
      - name: 'team-federation'
        slack_configs:
          - channel: '#federation-alerts'
            api_url: ${SLACK_WEBHOOK_URL}

redis:
  cluster:
    enabled: true
    slaveCount: 2

mongodb:
  replicaSet:
    enabled: true
    replicas: 3