global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dive25-api'
    static_configs:
      - targets: ['api:6969']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'
    scheme: 'http'

# NATO-specific alerting rules
rule_files:
  - 'nato_rules.yml'

# Kong-specific alerting rules
rule_files:
  - 'kong_rules.yml' 