global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dive25-api'
    static_configs:
      - targets: ['api:6969']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'
    scheme: 'http'

  # NATO-specific alerting rules
rule_files:
  - 'nato_rules.yml' 