services:
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/dive25?authSource=admin
      - STORAGE_PATH=/app/storage
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=dive25
      - DB_USER=${MONGO_ROOT_USER}
      - DB_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./storage:/app/storage
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6969/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/nato_docs
      - REDIS_HOST=redis
      - OPA_URL=http://opa:8181
    depends_on:
      - mongodb
      - redis
      - opa
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  mongodb:
    image: mongo:5
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=dive25
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' mongodb:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["mongod", "--bind_ip_all"]

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=:8181"
      - "/policies"
    volumes:
      - ./policies:/policies
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: 