# Production overrides
services:
  frontend:
    build: ../src/frontend
    environment:
      - NODE_ENV=production
      - API_URL=https://api.dive25.com

  backend:
    build: ../src/backend
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod

  db:
    environment:
      - POSTGRES_DB=dive25_prod