# Base configuration
services:
  frontend:
    build: ../src/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  backend:
    build: ../src/backend
    ports:
      - "${API_PORT:-6969}:6969"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Only the volumes we're actually using
volumes:
  postgres_data: