x-common-variables: &common-variables
  PING_IDENTITY_ACCEPT_EULA: "YES"
  PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
  PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
  PING_IDENTITY_PASSWORD: "2FederateM0re"
services:
  pingfederate:
    image: pingidentity/pingfederate:12.2.0-latest
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_PASSWORD=2FederateM0re
      - PA_ADMIN_PASSWORD_INITIAL=2FederateM0re
      - PF_ADMIN_USER_PASSWORD=2FederateM0re
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingfederate/instance/:/tmp/server-profile/server-profiles/pingfederate/
      - ./certificates:/opt/in/certificates
      - pingfederate-out:/opt/out
    tmpfs:
      - /tmp:exec,mode=1777
    networks:
      - dive25-net
    ports:
      - "9999:9999"  # Admin console
      - "9031:9031"  # Runtime port - changed from 9031
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  pingaccess:
    image: pingidentity/pingaccess:8.2.0-latest
    ports:
      - "9000:9000"  # Admin console
      - "3001:3000"  # Runtime port
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_PASSWORD=2FederateM0re
      - PA_ADMIN_PASSWORD_INITIAL=2FederateM0re
      - PA_ADMIN_USER_PASSWORD=2FederateM0re
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingaccess/instance/:/tmp/server-profile/server-profiles/pingaccess/
      - ./certificates:/opt/in/certificates
      - pingaccess-out:/opt/out
    tmpfs:
      - /tmp:exec,mode=1777
    networks:
      - dive25-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  pingdirectory:
    image: pingidentity/pingdirectory:10.2.0.0-latest
    ports:
      - "1636:636"
      - "1389:389"
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PD_ADMIN_USER_PASSWORD=2FederateM0re
    volumes:
      - ./licenses:/opt/in/licenses
      - ./server-profiles/pingdirectory/instance/:/tmp/server-profile/server-profiles/pingdirectory/
      - ./certificates:/opt/in/certificates
      - pingdirectory-out:/opt/out
    tmpfs:
      - /tmp:exec,mode=1777
    networks:
      - dive25-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/out/instance/bin/status.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3050:3000"  # Changed from 3000 to avoid conflict

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

networks:
  dive25-net:
    driver: bridge

volumes:
  pingfederate-out:
  pingaccess-out:
  pingdirectory-out: