# Development overrides
services:
  frontend:
    build: ../src/frontend
    volumes:
      - ../src/frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build: ../src/backend
    volumes:
      - ../src/backend:/app
      - /app/node_modules
    command: npm run dev

  db:
    ports:
      - "5432:5432"

volumes:
  postgres_dev_data:
  postgres_data:
  mongodb_data: