# PingDirectory common configuration (version 10.2.0-latest)
server:
  instanceName: "DIVE25-PD"
  version: "10.2.0-latest"
  bindAddress: "0.0.0.0"
  port: 389
  dataDirectory: "/opt/pingidentity/data"
  logsDirectory: "/opt/pingidentity/logs"
  replication:
    enabled: false

directory:
  baseDN: "dc=dive25,dc=com"
  schemaFile: "/opt/pingidentity/config/schema.ldif"
  attributeMappings:
    uniqueIdentifier: "uid"
    clearance: "clearance"
    countryOfAffiliation: "country"
    coiTags: "coiTags"
    lacvCode: "lacvCode"
  indices:
    - attribute: "uid"
      type: "equality"
    - attribute: "clearance"
      type: "equality"

initialData:
  file: "/opt/pingidentity/config/initial-users.ldif"

administrators:
  - username: "mike"
    password: "mike2222"
  - username: "aubrey"
    password: "aubrey456"
