# PingAccess common configuration (version 8.2.0-latest)
server:
  instanceName: "DIVE25-PA"
  version: "8.2.0-latest"
  bindAddress: "0.0.0.0"
  port: 8443
  dataDirectory: "/opt/pingidentity/data"
  logsDirectory: "/opt/pingidentity/logs"

reverseProxy:
  enabled: true
  proxyHeaders:
    - "X-Forwarded-For"
    - "X-Forwarded-Proto"
    - "X-Forwarded-Host"

accessControl:
  defaultPolicy: "deny"
  routes:
    - name: "WordPress_Frontend"
      path: "/wordpress/*"
      target: "http://wordpress:80"
      ssoRequired: true
      description: "Routes traffic to the WordPress front-end UI"
    - name: "Backend_API"
      path: "/api/*"
      target: "http://nodejs-api:3000"
      ssoRequired: true
      opaIntegration:
        enabled: true
        opaUrl: "http://opa:8181/v1/data/access_policy/allow"
      description: "Routes traffic to the Node.js API with OPA-based ABAC enforcement"

administrators:
  - username: "mike"
    password: "mike2222"
  - username: "aubrey"
    password: "aubrey456"
