# docker/monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'dive25-federation'
    static_configs:
      - targets: ['dive25-api:3000']
    metrics_path: '/metrics'

  - job_name: 'pingfederate'
    static_configs:
      - targets: ['pingfederate:9999']
    metrics_path: '/pf/monitor/metrics'
    basic_auth:
      username: ${PF_ADMIN_USERNAME}
      password: ${PF_ADMIN_PASSWORD}